version: '3.8'

services:
  app:
    build: .
    ports:
      - "3500:3500"
    depends_on:
      - db
    command: /bin/bash -c "sleep 20 && node index.js"
    environment:
      - PORT=3500
      - DATABASE_URL=postgres://postgres:postgres@db:5432/tailor
      - JWT_SECRET=tailorData


  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./pgData:/var/lib/postgresql/data
    